generic_hw_control_loop:
  loop_hz: 50
  cycle_time_error_threshold: 0.01

  # Settings for ros_control hardware interface
hardware_interface:
  joints:
      - rear_wheel_joint
      - front_steer_joint
  sim_control_mode: 0 # 0: position, 1: velocity

 
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

ackermann_control:
  type        : "ackermann_steering_controller/AckermannSteeringController"
  rear_wheel: 'rear_wheel_joint'
  front_steer: 'front_steer_joint'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation between the rear and the front, and diameter of the rear. 
  # These are both optional.
  # ackermann_steering_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter.
  wheel_separation_h : 0.22
  wheel_radius : 0.036

  # Wheel separation and radius multipliers for odometry calibration.
  wheel_separation_h_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Steer position angle multipliers for fine tuning.
  steer_pos_multiplier       : 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_link

  # Transform from odom -> base_link
  enable_odom_tf: true
  odom_frame_id: '/odom'

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.85  # m/s
      min_velocity           : -0.85 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.6  # m/s^2
      min_acceleration       : -1.6 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 1.0 # m/s^3

  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.6  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.6  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 1.5 # rad/s^3